### ISSUE TITLE
HU13: Como administrador quiero importar datos (especificar)

### ISSUE THREAD

**Issue by jisbruzzi** [matacos/mataco-control#31]
(materias? cursos? prioridades? estudiantes? docentes)
Esta historia consiste en proponer pantallas pero tb proponer formatos (especificar los campos que debe tener el csv)

**Comment by jisbruzzi** [comment]
[2h]

**Comment by Camilaf** [comment]
Para la 13.1, es necesario que el cliente sepa eso? Creo que es algo más interno

**Comment by jisbruzzi** [comment]
@Camilaf un script python es portable, por eso especifiqué

**Comment by jisbruzzi** [comment]
[15m]
