### ISSUE TITLE
HU?? Como administrador, quiero configurar alertas automáticas (especificar)

### ISSUE THREAD

**Issue by jisbruzzi** [matacos/mataco-control#36]

**Comment by Camilaf** [comment]
No sé bien a qué se refiere. Tener opciones para ver cuándo enviar alertas automáticamente? Como cuando cancelás un final?

**Comment by jisbruzzi** [comment]
@Camilaf Creo que el único parámetro que me imagino es la cantidad de días antes de un final que quiero que se alerten los alumnos, pero eso sería más bien alumno a alumno, al administrador no le interesa esto. 
Creo que simplemente habría que dejar los eventos que pusimos en HU16 y HU17 y preguntar si quiere más.
La otra es poner un ABM de notificaciones del lado de android
